[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
publish = ".next"
command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm -F docs... build"
